replicas: 1
namespace: "default"

container:
  image: "your/flask-image"

db:
  user: "your_db_user"
  password: "your_db_password"
  host: "your_db_host"
  name: "your_db_name"

loadBalancerAnnotations:
  kubernetes.io/ingress.global-static-ip-name: "ip-geolocation"

reserved_ip: reserved