name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  DB_USER:  ${{ secrets.DB_USER }}
  DB_PASS:  ${{ secrets.PASS }}
  DB_HOST:  ${{ secrets.HOST }}
  DB_NAME:  ${{ secrets.NAME }}
  # DOCKER_USER: ${{ secrets.DOCKER_USER }}
  # DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  
  CHART_PATH: ./infra/helm/deploy/app
  
  GAR_LOCATION: us-useast1
  GKE_CLUSTER: cluster-1   
  GKE_ZONE: us-useast1-a  
  HELM_NAME: ip-geolocation 
  REPOSITORY: registry
  IMAGE: ipgeolocation
  NAMESPACE: prod

  
  

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    
    # Authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    
    - name: Docker configuration
      run: |-
        docker login -u oauth2accesstoken -p ${{steps.auth.outputs.access_token}}  https://$GAR_LOCATION-docker.pkg.dev

    
    
    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}






    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"







    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $PROJECT_ID
        helm upgrade -i $HELM_NAME $CHART_PATH \
          --set container.image="$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          --set db.user=$DB_USER \       
          --set db.password=$DB_PASS \          
          --set db.host=$DB_HOST \          
          --set db.name=$DB_NAME \          
          --wait
        kubectl get all -n $NAMESPACE
